swipe:
  3:
    left:
      command: hyprctl dispatch workspace e-1
    right:
      command: hyprctl dispatch workspace e+1
  4:
    up:
      command: pactl set-sink-volume @DEFAULT_SINK@ +5%
    down:
      command: pactl set-sink-volume @DEFAULT_SINK@ -5%

threshold:
  swipe: 0.2

interval:
  swipe: 0.3