#!/bin/bash

STATE_FILE="/tmp/wallpaper_current"
WALLPAPER_DIR="/home/teaguy21/Videos/LiveWallpaper"
WALLPAPER_PREFIX="live-wallpaper"
SOLID_COLOR="#000000"

# path for autogenerated solid PNG used when hyprpaper is available
SOLID_PNG="$HOME/Pictures/Wallpapers/black.png"

if [ ! -f "$STATE_FILE" ]; then
    echo "solid" > "$STATE_FILE"
fi

CURRENT_STATE=$(cat "$STATE_FILE")

WALLPAPERS=($WALLPAPER_DIR/${WALLPAPER_PREFIX}*)
WALLPAPER_COUNT=${#WALLPAPERS[@]}

# helper: is file a video (simple ext check)
is_video() {
    case "${1,,}" in
        *.mp4|*.mkv|*.webm|*.mov) return 0 ;;
        *) return 1 ;;
    esac
}

# helper: set wallpaper video via mpvpaper if needed
set_wallpaper_video() {
    FILE="$1"
    mpvpaper -o "no-audio loop video-scale=oversample panscan=1.0" eDP-1 "$FILE" >/dev/null 2>&1 &
    mpvpaper -o "no-audio loop video-scale=oversample panscan=1.0" HDMI-A-1 "$FILE" >/dev/null 2>&1 &
}

if [ -z "$1" ] || [ "$1" != "--initial" ]; then
    if [ "$CURRENT_STATE" = "solid" ]; then
        # switching from solid -> animated: pick first wallpaper and set
        pkill hyprpaper 2>/dev/null || true
        if [ $WALLPAPER_COUNT -gt 0 ]; then
            FIRST="${WALLPAPERS[0]}"
            if is_video "$FIRST"; then
                set_wallpaper_video "$FIRST"
            else
                set_wallpaper_image "$FIRST"
            fi
            echo "animated:0" > "$STATE_FILE"
        fi
    elif [[ "$CURRENT_STATE" == animated:* ]]; then
        CURRENT_INDEX=${CURRENT_STATE#animated:}

        pkill mpvpaper 2>/dev/null || true
        pkill hyprpaper 2>/dev/null || true

        NEXT_INDEX=$((CURRENT_INDEX + 1))

        if [ $NEXT_INDEX -ge $WALLPAPER_COUNT ]; then
            # wrap to solid color
            pkill mpvpaper 2>/dev/null || true
            pkill hyprpaper 2>/dev/null || true
            set_wallpaper_image "$SOLID_PNG"
            echo "solid" > "$STATE_FILE"
        else
            NEXT_FILE="${WALLPAPERS[$NEXT_INDEX]}"
            if is_video "$NEXT_FILE"; then
                set_wallpaper_video "$NEXT_FILE"
            else
                set_wallpaper_image "$NEXT_FILE"
            fi
            echo "animated:$NEXT_INDEX" > "$STATE_FILE"
        fi
    fi
else
    pkill mpvpaper 2>/dev/null || true
    pkill hyprpaper 2>/dev/null || true
    
    INITIAL_WALLPAPER="$HOME/Pictures/Wallpapers/thunderstorm.jpg"
    if [ -f "$INITIAL_WALLPAPER" ]; then
        set_wallpaper_image "$INITIAL_WALLPAPER"
    else
        set_wallpaper_image "$SOLID_PNG"
    fi
    echo "solid" > "$STATE_FILE"
fi

# Properly exit the script
exit 0