# Font config:
font.normal = { family = "FiraCode Nerd Font ", style = "Retina"}
font.size = 11.5

# Window
window.padding = {x = 15, y = 15}
window.decorations = "None"
window.opacity = 0.95

# Themes
[general]
import = [
    "~/.config/alacritty/themes/themes/ayu_dark.toml"
]

